fof(rule_1, axiom, ![X0]: (~((l_s(X0) | Repair_Simple(X0)) & (x3_e(X0)))))
fof(rule_2, axiom, ![X0]: (~((l_s(X0)) & (tau(X0)))))
fof(rule_3, axiom, ![X0]: (~((Repair_Complex(X0)) & (tau(X0)))))
fof(rule_4, axiom, ?[X0]: (x3_s(X0)))
fof(rule_5, axiom, ![X0]: (~((l_s(X0) | Repair_Complex(X0)) & (l_s(X0) | Repair_Simple(X0)))))
fof(rule_6, axiom, ![X0]: (~((Register(X0)) & (a2_s(X0) | a2_e(X0)))))
fof(rule_7, axiom, ![X0]: (~((Repair_Simple(X0)) & (tau(X0)))))
fof(rule_8, axiom, ![X1]: ((a2_s(X1)) => (?[X0]: (Inform_User(X0)) & ?[X2]: (x3_s(X2) | x3_e(X2)))))
fof(rule_9, axiom, ![X0]: (~((Register(X0)) & (Archive_Repair(X0)))))
fof(rule_10, axiom, ![X1]: ((a2_s(X1) | a2_e(X1)) => ?[X0]: (Archive_Repair(X0))))
fof(rule_11, axiom, ![X0]: (~((a2_s(X0)) & ((Inform_User(X0)) | (x3_s(X0) | x3_e(X0))))))
fof(rule_12, axiom, ![X0]: (~((l_s(X0) | Test_Repair(X0)) & (l_s(X0) | Repair_Simple(X0)))))
fof(rule_13, axiom, ?[X0]: (l_s(X0)))
fof(rule_14, axiom, ![X0]: (~((l_s(X0)) & (Repair_Simple(X0)))))
fof(rule_15, axiom, ![X0]: (~((Analyze_Defect(X0)) & (End(X0)))))
fof(rule_16, axiom, ![X0]: (~((l_s(X0) | Repair_Complex(X0)) & (x3_e(X0)))))
fof(rule_17, axiom, ![X1]: ((Inform_User(X1)) => ?[X0]: (a2_e(X0))))
fof(rule_18, axiom, ![X0]: (~((x3_s(X0)) & (l_s(X0) | Repair_Complex(X0)))))
fof(rule_19, axiom, ![X1]: ((Register(X1)) => ?[X0]: (Analyze_Defect(X0))))
fof(rule_20, axiom, ![X1]: ((l_s(X1)) => ?[X0]: (Repair_Complex(X0))))
fof(rule_21, axiom, ![X0]: (~((l_s(X0) | Test_Repair(X0)) & (l_s(X0) | Repair_Complex(X0)))))
fof(rule_22, axiom, ![X0]: (~((x3_s(X0)) & (l_s(X0) | Repair_Simple(X0)))))
fof(rule_23, axiom, ![X1]: ((l_s(X1)) => ?[X0]: (Repair_Simple(X0))))
fof(rule_24, axiom, ![X1]: ((Analyze_Defect(X1)) => ?[X0]: (a2_s(X0) | a2_e(X0))))
fof(rule_25, axiom, ![X1]: ((l_s(X1)) => ?[X0]: (Test_Repair(X0))))
fof(rule_26, axiom, ![X0]: (~((Analyze_Defect(X0)) & (Archive_Repair(X0)))))
fof(rule_27, axiom, ![X1]: ((Repair_Complex(X1)) => ((?[X0]: (tau(X0)) & ?[X2]: (Repair_Complex(X2))) | (~(?[X3]: (tau(X3)))))))
fof(rule_28, axiom, ![X0]: (~((l_s(X0)) & (Repair_Complex(X0)))))
fof(rule_29, axiom, ![X0]: (~((Test_Repair(X0)) & (tau(X0)))))
fof(rule_30, axiom, ![X1]: ((x3_s(X1) | x3_e(X1)) => ?[X0]: (a2_e(X0))))
fof(rule_31, axiom, ![X0]: (~(((Inform_User(X0)) | (x3_s(X0) | x3_e(X0))) & (a2_e(X0)))))
fof(rule_32, axiom, ?[X0]: (a2_s(X0)))
fof(rule_33, axiom, ![X1]: ((Repair_Simple(X1)) => ((?[X0]: (tau(X0)) & ?[X2]: (Repair_Simple(X2))) | (~(?[X3]: (tau(X3)))))))
fof(rule_34, axiom, ?[X0]: (Register(X0)))
fof(rule_35, axiom, ![X0]: (~((Archive_Repair(X0)) & (End(X0)))))
fof(rule_36, axiom, ![X0]: (~((Register(X0)) & (Analyze_Defect(X0)))))
fof(rule_37, axiom, ![X0]: (~((a2_s(X0) | a2_e(X0)) & (End(X0)))))
fof(rule_38, axiom, ![X1]: ((Test_Repair(X1)) => ((?[X0]: (tau(X0)) & ?[X2]: (Test_Repair(X2))) | (~(?[X3]: (tau(X3)))))))
fof(rule_39, axiom, ![X0]: (~((a2_s(X0) | a2_e(X0)) & (Archive_Repair(X0)))))
fof(rule_40, axiom, ![X1]: ((tau(X1)) => ?[X0]: (Repair_Complex(X0))))
fof(rule_41, axiom, ![X1]: ((Archive_Repair(X1)) => ?[X0]: (End(X0))))
fof(rule_42, axiom, ![X0]: (~((x3_s(X0)) & (l_s(X0) | Test_Repair(X0)))))
fof(rule_43, axiom, ![X1]: ((x3_s(X1)) => ((?[X0]: (l_s(X0) | Test_Repair(X0)) & ~(?[X2]: (l_s(X2) | Repair_Complex(X2))) & ~(?[X3]: (l_s(X3) | Repair_Simple(X3)))) | (~(?[X4]: (l_s(X4) | Test_Repair(X4))) & ?[X5]: (l_s(X5) | Repair_Complex(X5)) & ~(?[X6]: (l_s(X6) | Repair_Simple(X6))) | (~(?[X7]: (l_s(X7) | Test_Repair(X7))) & ~(?[X8]: (l_s(X8) | Repair_Complex(X8))) & ?[X9]: (l_s(X9) | Repair_Simple(X9)))))))
fof(rule_44, axiom, ![X1]: (((l_s(X1) | Test_Repair(X1)) | (l_s(X1) | Repair_Complex(X1)) | (l_s(X1) | Repair_Simple(X1))) => ?[X0]: (x3_e(X0))))
fof(rule_45, axiom, ![X0]: (~((Register(X0)) & (End(X0)))))
fof(rule_46, axiom, ![X0]: (~((l_s(X0) | Test_Repair(X0)) & (x3_e(X0)))))
fof(rule_47, axiom, ![X1]: ((tau(X1)) => ?[X0]: (Test_Repair(X0))))
fof(rule_48, axiom, ![X0]: (~((Analyze_Defect(X0)) & (a2_s(X0) | a2_e(X0)))))
fof(rule_49, axiom, ![X1]: ((tau(X1)) => ?[X0]: (Repair_Simple(X0))))
fof(rule_50, axiom, ![X0]: (~((x3_s(X0)) & (x3_e(X0)))))
fof(rule_51, axiom, ![X0]: (~((l_s(X0)) & (Test_Repair(X0)))))